version: '3.8'

services:
  # 1. Banco de Dados SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: scoops-sql-server
    environment:
      - ACCEPT_EULA=Y
      # A senha agora vem do arquivo .env
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - scoops-network
    volumes:
      - sql_data:/var/opt/mssql

  # 2. Microsserviço de Autenticação
  auth-api:
    build:
      context: ./Scoops.Auth.API
      dockerfile: Dockerfile
    container_name: scoops-auth-api
    ports:
      - "5001:8080"
    environment:
      # Injetamos a senha do banco na string de conexão
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ScoopsAuthDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      # Credenciais do Admin injetadas
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      # Configuração JWT segura
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=ScoopsAuth
      - Jwt__Audience=ScoopsManagement
      - Jwt__ExpireHours=2
    depends_on:
      - sqlserver
    networks:
      - scoops-network

  # 3. Microsserviço de Gestão
  management-api:
    build:
      context: ./Scoops.Management.API
      dockerfile: Dockerfile
    container_name: scoops-management-api
    ports:
      - "5000:8080"
    environment:
      # Mesma injeção de senha do banco
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ScoopsManagementDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      # A chave deve ser IDÊNTICA à da Auth API para validar o token
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=ScoopsAuth
      - Jwt__Audience=ScoopsManagement
    depends_on:
      - sqlserver
    networks:
      - scoops-network
    volumes:
      - ./uploads:/app/wwwroot/images

  # 4. Frontend React
  frontend:
    build:
      context: ./scoops-web
      dockerfile: Dockerfile
    container_name: scoops-frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-api
      - management-api
    networks:
      - scoops-network

networks:
  scoops-network:
    driver: bridge

volumes:
  sql_data: